http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect-router:
      entryPoints:
        - web
      middlewares:
        - redirect
      rule: PathPrefix(`/`)
      service: app