http:
  middlewares:
    security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"

  routers:
    app:
      entryPoints:
        - web
        - websecure
      middlewares:
        - security
      service: app-service
      rule: "PathPrefix(`/`)"
      tls:
        certResolver: letsencrypt

  services:
    app-service:
      loadBalancer:
        servers:
          - url: "http://app:3000"