name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT}}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/flexidbio/flexidb:latest
            ghcr.io/flexidbio/flexidb:${{ github.sha }}
            ghcr.io/flexidbio/flexidb:v${{ steps.get_version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.source=flexidbio/flexidb
            org.opencontainers.image.description=FlexiDB - A flexible database management system
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=v${{ steps.get_version.outputs.VERSION }}
          public: true
          
          